_target_: src.eval.agents.openai_langchain_agent.OpenAILangchainAgent
name: planning
model_name: gpt-4-1106-preview
temperature: 0
model_kwargs:
  seed: 76097149
prompt:
  _target_: src.eval.prompts.planning_prompt.PlanningPrompt
  model_name: gpt-4-1106-preview
  temperature: 0
  model_kwargs:
    seed: 76097149
  planning_system_prompt_path: configs/template_generation/prompts/planning_planning_system_prompt_v2.md
  execution_system_prompt_path: configs/template_generation/prompts/planning_execution_system_prompt_v2.md