_target_: src.eval.agents.reflexion_agent.ReflexionAgent
model_name: gpt-3.5-turbo-1106
temperature: 0
model_kwargs:
  seed: 76097149
value_threshold: 1.0,  # threshold for evaluation; when reached, the loop will exit
max_num_iterations: 2,  # maximum number of iterations; when reached, the loop will exit
prompt:
  _target_: src.eval.prompts.reflexion_prompt.ReflexionPrompt
  action_prompt: |
    You are given basic api for operation with files in software engineering empty project. 
    Your goal is generate template project by given description.
  evaluator_prompt: |
    Given a project template description and a step of generation process, give a judgement if the step is correct, i.e. 
    1) the action aligns with the main goal and description of project template; 
    2) action fits current project structure and does not break it; 
    3) action extends current project functionality and does not break it;
  self_reflexion_prompt: |
    You were given basic api for operation with files in software engineering empty project. 
    Your goal was to generate template project by given description.
    You were unsuccessful.
