name: adapt
data_src:
  _target_: src.eval.data.hf.HFDataSource
  cache_dir: null
  hub_name: JetBrains-Research/template-generation
  configs:
    - java
    - kt
  split: test
output_path: /Users/Maria.Tigina/PycharmProjects/agents-eval-github/gen_template
env:
  _target_: src.eval.envs.http_env.HttpEnv
  host: '127.0.0.1'
  port: '5050'
agent:
  _target_: src.eval.agents.adapt_agent.ADaPTAgent
  model_name: gpt-3.5-turbo-1106
  temperature: 0
  max_depth: 3  # maximum decomposition depth
  executor_max_iterations: 2  # maximum number of iterations for the executor; when reached, the loop will exit
  model_kwargs:
    seed: 76097149
  prompt:
    _target_: src.eval.prompts.adapt_prompt.ADaPTPrompt
    executor_prompt: |
      You are given basic api for operation with files in software engineering empty project. 
      Your goal is generate template project by given description.
    agent_planner_prompt: |
      Here is the essence of the original task:
    simple_planner_prompt: |
      Here is the essence of the original task: