data_path: /Users/Maria.Tigina/PycharmProjects/agents-eval-data
repos_path: /Users/Maria.Tigina/PycharmProjects/agents-eval-data/repos
projects_path: /Users/Maria.Tigina/PycharmProjects/agents-eval-data/ide_templates
archives_path: /Users/Maria.Tigina/PycharmProjects/agents-eval-data/ide_templates_arch
github_tokens_path: /Users/Maria.Tigina/PycharmProjects/agents-eval-data/tokens.txt
splits:
  java: [
    'amiya-pattnaik/selenium-cucumber-java',
  ]
  kt: [
    'arkivanov/decompose-multiplatform-template',
  ]
  android: [
    'amzn/firetv-sample-touch-app'
  ]
  py: [
      '12rambau/pytest-copie'
  ]