repos_path: /Users/Maria.Tigina/PycharmProjects/agents-eval-github/repos
gen_templates_path: /Users/Maria.Tigina/PycharmProjects/agents-eval-github/gen_templates
gen_templates_results_path: /Users/Maria.Tigina/PycharmProjects/agents-eval-github/gen_templates_results