repos_path: /Users/Maria.Tigina/PycharmProjects/agents-eval-data/repos
gen_templates_path: /Users/Maria.Tigina/PycharmProjects/agents-eval-data/template_generation
metrics_path: /Users/Maria.Tigina/PycharmProjects/agents-eval-data/metrics