name: planning-gpt-4-1106-preview
env:
  _target_: src.eval.envs.http_env.HttpEnv
  host: '127.0.0.1'
  port: '5050'
agent:
  _target_: src.eval.agents.openai_langchain_agent.OpenAiLangchainAgent
  prompt:
    _target_: src.eval.prompts.planning_prompt.PlanningPrompt
    model_name: gpt-4-1106-preview
    temperature: 0.8
    model_kwargs:
      seed: 76097149
    planning_system_prompt: |
      Devise a detailed step-by-step action plan for handling the task at hand, clearly emphasizing the sequential order of operations. 
      Your plan should:
      - Specify the task's end goal and break down the process into individual actions, using bullet points for clarity.
      - Abstractly describe the logical and conditional flow between actions.
      - Do not execute any functions or write any code. This is a planning-only phase, intended to create a blueprint for the execution phase.
    execution_system_prompt: |
      Execute the following detailed action plan methodically. 
      For each step of the plan:
      - Call the appropriate function with the required arguments, corresponding directly to the outlined plan's next action.
      - Evaluate the function call's result and adjust the next steps accordingly, maintaining fidelity to the plan's intended sequence.
      - If a function call fails or produces undesired outcomes, stop execution process.
      - Persist through different strategies, avoiding repetition of unsuccessful attempts, until the task is completed or a maximum of 50 steps have been taken.
      - Document solely the function calls and their outcomes. Refrain from additional commentary or explanatory text during this execution phase.
      Begin execution with the plan start point, adhering strictly to the prescribed operations.
  model_name: gpt-4-1106-preview
  temperature: 0.8
  model_kwargs:
    seed: 76097149
data_src:
  _target_: src.eval.data.hf.HFDataSource
  cache_dir: null
  hub_name: JetBrains-Research/template-generation
  configs:
  - java
  - kt
  split: test
output_path: /Users/Maria.Tigina/PycharmProjects/agents-eval-github/gen_template