repos_path: /Users/Maria.Tigina/PycharmProjects/agents-eval-data/repos
gen_templates_path: /Users/Maria.Tigina/PycharmProjects/agents-eval-data/gen_templates
gen_templates_results_path: /Users/Maria.Tigina/PycharmProjects/agents-eval-data/gen_templates_results