env:
  _target_: src.eval.envs.http_env.HttpEnv
  host: '127.0.0.1'
  port: '5050'
agent:
  _target_: src.eval.agents.openai_langchain_agent.OpenAiLangchainAgent
  prompt:
    _target_: src.eval.prompts.planning_prompt.PlanningPrompt
    model_name: gpt-3.5-turbo-1106
    temperature: 0.8
    model_kwargs:
      seed: 76097149
  model_name: gpt-3.5-turbo-1106
  temperature: 0.8
  model_kwargs:
    seed: 76097149
data:
  _target_: src.eval.data.hf.HFDataSource
  cache_dir: null
  hub_name: JetBrains-Research/template-generation
  configs:
  - java
  - kt
  split: test
output_path: /Users/Maria.Tigina/PycharmProjects/agents-eval-data/eval_results

