data_path: /Users/Maria.Tigina/PycharmProjects/agents-eval-data
repos_path: /Users/Maria.Tigina/PycharmProjects/agents-eval-data/repos
gen_templates_path: /Users/Maria.Tigina/PycharmProjects/agents-eval-data/gen_templates
gen_templates_results_path: /Users/Maria.Tigina/PycharmProjects/agents-eval-data/gen_templates_result
github_tokens_path: /Users/Maria.Tigina/PycharmProjects/agents-eval-data/tokens.txt
docker_image: 'mariatigina/file-system-service:latest'
docker_host: '127.0.0.1'
docker_port: '5050'
splits:
  java: [0]
  kt: [426]